name: lede
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      config:
        description: '请输入配置文件名称'
        required: true
        default: 'x86_64.config'
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: 下载安装编译所需套件
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
        git clone https://github.com/coolsnowwolf/lede openwrt
        cd openwrt
        sed -i '1i src-git liuran001_packages https://github.com/liuran001/openwrt-packages' ./feeds.conf.default
    - name: 配置定制过程
      env:
        CONFIG_FILE: "${{ github.event.inputs.config }}"
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        sed -i '1i CONFIG_KERNEL_BUILD_USER="fxhack"' openwrt/.config
        sed -i '1i CONFIG_GRUB_TITLE="OpenWrt by fxhack"' openwrt/.config
        chmod +x ./diy.sh && ./diy.sh
    - name: 开始编译固件
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a   
        make defconfig
        echo -e "$(nproc) thread build."
        make download -j$(nproc)
        make -j$(nproc) V=s
        echo -e "done!"
    - name : 上传固件
      uses: actions/upload-artifact@master
      with:
        name: openwrt
        path: openwrt/bin
